systems = [
  {
    name: "Col 285 Sector BS-I c10-11",
    body: "ABCD 2 a",
    coords: { x: -154.46875, y: 141.25, z: 55.875 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "HIP 82068",
    body: "5 c",
    coords: { x: -125.375, y: 122.3125, z: 78.28125 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Osseus Discus",
    ],
    cat: [],
  },
  {
    name: "HIP 83863",
    body: "AB 1 e",
    coords: { x: -70.3125, y: 75.125, z: 150.625 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "HIP 84676",
    body: "5 b",
    coords: { x: -72.15625, y: 70.8125, z: 190.21875 },
    infos: "",
    biologicals: [
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "HIP 86940",
    body: "2 a",
    coords: { x: -119.9375, y: 70.125, z: 178.875 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Acurus",
    body: "A 3",
    coords: { x: -142.46875, y: 10.40625, z: 102.65625 },
    infos: "",
    biologicals: ["Clypeus Margaritus", "Osseus Discus", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Col 285 Sector JY-H c10-27",
    body: "B 5 a",
    coords: { x: -178.65625, y: -0.34375, z: 58.78125 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Col 285 Sector GK-K b23-8",
    body: "C 1",
    coords: { x: -180, y: -16.40625, z: 148.9375 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Margaritus",
      "Osseus Discus",
      "Stratum Tectonicas",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Col 285 Sector ID-G a54-2",
    body: "A 2",
    coords: { x: -84.90625, y: -43.6875, z: 226.0625 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Stratum Tectonicas", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Kwatee",
    body: "C 6",
    coords: { x: -41, y: -51.40625, z: 167.53125 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Margaritus",
      "Stratum Tectonicas",
    ],
    cat: [],
  },
  {
    name: "Bridge",
    body: "1",
    coords: { x: -83.4375, y: -100.21875, z: 95.0625 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Stratum Tectonicas", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Harma",
    body: "A 7 f",
    coords: { x: -99.25, y: -100.96875, z: 20.40625 },
    infos: "",
    biologicals: [
      "Clypeus Lacrimam",
      "Frutexa Acus",
      "Osseus Pellebantus",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Daruwutja",
    body: "B 4",
    coords: { x: -81.75, y: -48.53125, z: -62.4375 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Clypeus Margaritus"],
    cat: [],
  },
  {
    name: "Daruwutja",
    body: "B 5",
    coords: { x: -81.75, y: -48.53125, z: -62.4375 },
    infos: "",
    biologicals: ["Clypeus Margaritus", "Stratum Tectonicas", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Lyncis Sector CL-Y c14",
    body: "ABC 1 c",
    coords: { x: -115.90625, y: 38.9375, z: -151.90625 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Recepta Deltahedronix",
      "Stratum Cucumisis",
    ],
    cat: [],
  },
  {
    name: "Arietis Sector YU-X b1-4",
    body: "B 6",
    coords: { x: -71, y: -9.0625, z: -166.8125 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Margaritus",
      "Stratum Tectonicas",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Hyades Sector YU-Y d76",
    body: "1 b",
    coords: { x: -66.125, y: -20.78125, z: -207.375 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Hyades Sector YU-Y d76",
    body: "1 c",
    coords: { x: -66.125, y: -20.78125, z: -207.375 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Hyades Sector AL-X c1-24",
    body: "A 3",
    coords: { x: -43.6875, y: 12.59375, z: -208.84375 },
    infos: "",
    biologicals: ["Aleoida Gravis", "Clypeus Margaritus", "Stratum Tectonicas"],
    cat: [],
  },
  {
    name: "HIP 22633",
    body: "3 a",
    coords: { x: -29.46875, y: -27.96875, z: -207.03125 },
    infos: "",
    biologicals: [
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "HIP 20415",
    body: "11 b",
    coords: { x: -47.0625, y: -52.96875, z: -225.5 },
    infos: "",
    biologicals: ["Frutexa Acus", "Tubus Compagibus"],
    cat: [],
  },
  {
    name: "HIP 20415",
    body: "11 d",
    coords: { x: -47.0625, y: -52.96875, z: -225.5 },
    infos: "",
    biologicals: ["Frutexa Acus", "Tubus Compagibus"],
    cat: [],
  },
  {
    name: "HIP 20415",
    body: "7 c",
    coords: { x: -47.0625, y: -52.96875, z: -225.5 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Arietis Sector ZE-A d74",
    body: "1 d",
    coords: { x: -94.5, y: -83.78125, z: -207.125 },
    infos: "",
    biologicals: [
      "Clypeus Lacrimam",
      "Frutexa Acus",
      "Osseus Pellebantus",
      "Stratum Cucumisis",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "HIP 21946",
    body: "6 b",
    coords: { x: 1.53125, y: -45.09375, z: -147.875 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Speculumi",
      "Osseus Pellebantus",
      "Stratum Cucumisis",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "HR 1385",
    body: "6 b",
    coords: { x: -6.78125, y: -56.59375, z: -154.65625 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "HR 1385",
    body: "6 c",
    coords: { x: -6.78125, y: -56.59375, z: -154.65625 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "HR 1385",
    body: "6 d",
    coords: { x: -6.78125, y: -56.59375, z: -154.65625 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Osseus Discus", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Hyades Sector GB-W b2-5",
    body: "AB 5",
    coords: { x: 19.59375, y: -49.0625, z: -223 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Stratum Tectonicas", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "HIP 26761",
    body: "5 a",
    coords: { x: 12, y: -8.625, z: -184.625 },
    infos: "",
    biologicals: ["Clypeus Lacrimam", "Frutexa Sponsae", "Osseus Discus"],
    cat: [],
  },
  {
    name: "HIP 26761",
    body: "5 c",
    coords: { x: 12, y: -8.625, z: -184.625 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Shoribelu",
    body: "5 b",
    coords: { x: -3.4375, y: 23.78125, z: -161.71875 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Shoribelu",
    body: "5 c",
    coords: { x: -3.4375, y: 23.78125, z: -161.71875 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Osseus Discus", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Shoribelu",
    body: "9 e",
    coords: { x: -3.4375, y: 23.78125, z: -161.71875 },
    infos: "",
    biologicals: ["Aleoida Coronamus", "Frutexa Acus"],
    cat: [],
  },
  {
    name: "HIP 28774",
    body: "AB 10 e",
    coords: { x: 1.84375, y: 6.96875, z: -82.9375 },
    infos: "",
    biologicals: [
      "Clypeus Lacrimam",
      "Frutexa Acus",
      "Osseus Pellebantus",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Col 285 Sector ST-P c6-11",
    body: "A 4",
    coords: { x: 104.75, y: 135.09375, z: -75.1875 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Margaritus",
      "Stratum Tectonicas",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Aleutes",
    body: "B 2",
    coords: { x: 4.5625, y: 148.09375, z: -54.25 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Margaritus",
      "Stratum Tectonicas",
    ],
    cat: [],
  },
  {
    name: "Col 285 Sector YK-M c8-9",
    body: "1",
    coords: { x: 95.25, y: 191.90625, z: 4.71875 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Margaritus",
      "Osseus Pellebantus",
      "Stratum Tectonicas",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "HIP 56960",
    body: "3 a",
    coords: { x: 80.78125, y: 98.6875, z: 8.125 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Borfor",
    body: "1 c",
    coords: { x: -1.09375, y: 21.21875, z: 85.25 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Osseus Discus", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Borfor",
    body: "1 d",
    coords: { x: -1.09375, y: 21.21875, z: 85.25 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Arvirisa",
    body: "C 4",
    coords: { x: 15.90625, y: 9.78125, z: 87.34375 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Margaritus",
      "Stratum Tectonicas",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Chersem",
    body: "2",
    coords: { x: 46.53125, y: 17.125, z: 136.71875 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Osseus Pellebantus",
      "Stratum Tectonicas",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "HIP 86086",
    body: "4 a",
    coords: { x: -8.96875, y: 11.34375, z: 181.53125 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Lacrimam",
      "Frutexa Acus",
      "Osseus Pellebantus",
    ],
    cat: [],
  },
  {
    name: "HR 6015",
    body: "3 c",
    coords: { x: 75.4375, y: 25.75, z: 195.46875 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Col 285 Sector WE-Q d5-88",
    body: "A 4",
    coords: { x: 145.375, y: 31.28125, z: 109.5625 },
    infos: "",
    biologicals: [
      "Clypeus Margaritus",
      "Osseus Pellebantus",
      "Stratum Tectonicas",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Kherthaje",
    body: "3 e",
    coords: { x: 105.625, y: 12.78125, z: 72.78125 },
    infos: "",
    biologicals: [
      "Clypeus Speculumi",
      "Frutexa Acus",
      "Osseus Pellebantus",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Antliae Sector IM-W d1-129",
    body: "4",
    coords: { x: 150.71875, y: 13.375, z: 61.34375 },
    infos: "",
    biologicals: ["Aleoida Gravis", "Clypeus Margaritus", "Stratum Tectonicas"],
    cat: [],
  },
  {
    name: "Setati",
    body: "A 1",
    coords: { x: 151.90625, y: 1.875, z: 74.71875 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Clypeus Margaritus", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "Col 285 Sector BG-E c12-16",
    body: "A 8 a",
    coords: { x: 168.59375, y: -47.46875, z: 148 },
    infos: "",
    biologicals: [
      "Clypeus Lacrimam",
      "Osseus Pellebantus",
      "Stratum Cucumisis",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Col 285 Sector SI-J c9-12",
    body: "5 e",
    coords: { x: 198.96875, y: -86.25, z: 46.3125 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Lacrimam",
      "Osseus Pellebantus",
      "Stratum Cucumisis",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "HIP 37068",
    body: "1 b",
    coords: { x: 195.03125, y: -50.9375, z: -17.4375 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Osseus Discus", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "HIP 37068",
    body: "6 a",
    coords: { x: 195.03125, y: -50.9375, z: -17.4375 },
    infos: "",
    biologicals: ["Frutexa Acus", "Tubus Compagibus"],
    cat: [],
  },
  {
    name: "HIP 37068",
    body: "6 b",
    coords: { x: 195.03125, y: -50.9375, z: -17.4375 },
    infos: "",
    biologicals: ["Frutexa Acus", "Tubus Compagibus"],
    cat: [],
  },
  {
    name: "Wuning",
    body: "A 1",
    coords: { x: 169.53125, y: -20.4375, z: -16.9375 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Margaritus",
      "Stratum Tectonicas",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Col 285 Sector ZE-P c6-21",
    body: "B 4",
    coords: { x: 159.5, y: 36.28125, z: -92.0625 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Margaritus",
      "Osseus Discus",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "HIP 26060",
    body: "5 a",
    coords: { x: 109.3125, y: -74.46875, z: -98.625 },
    infos: "",
    biologicals: [
      "Clypeus Lacrimam",
      "Frutexa Acus",
      "Osseus Pellebantus",
      "Stratum Cucumisis",
    ],
    cat: [],
  },
  {
    name: "BD-08 535",
    body: "1 c",
    coords: { x: 5.34375, y: -82, z: -56.625 },
    infos: "",
    biologicals: [
      "Clypeus Lacrimam",
      "Osseus Pellebantus",
      "Stratum Cucumisis",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Hyades Sector JR-W c1-6",
    body: "1 a",
    coords: { x: 12.1875, y: -163.375, z: -188.75 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Lacrimam",
      "Stratum Cucumisis",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "HIP 9331",
    body: "AB 5 c",
    coords: { x: 38.875, y: -236.0625, z: -53.96875 },
    infos: "",
    biologicals: [
      "Clypeus Lacrimam",
      "Frutexa Acus",
      "Osseus Pellebantus",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "HIP 772",
    body: "2 b",
    coords: { x: 4.875, y: -189.375, z: 35.78125 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Osseus Discus", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "HIP 772",
    body: "2 c",
    coords: { x: 4.875, y: -189.375, z: 35.78125 },
    infos: "",
    biologicals: ["Cactoida Vermis", "Osseus Discus", "Tussock Virgam"],
    cat: [],
  },
  {
    name: "El Tio",
    body: "5 a",
    coords: { x: 36.96875, y: -117.5625, z: 25.4375 },
    infos: "",
    biologicals: [
      "Clypeus Speculumi",
      "Frutexa Acus",
      "Osseus Pellebantus",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "HIP 105439",
    body: "AB 4 e",
    coords: { x: 25.96875, y: -105.90625, z: 104.65625 },
    infos: "",
    biologicals: [
      "Cactoida Vermis",
      "Clypeus Lacrimam",
      "Frutexa Sponsae",
      "Tussock Virgam",
    ],
    cat: [],
  },
  {
    name: "Faroras",
    body: "3 d",
    coords: { x: 94.4375, y: -93.03125, z: 81.71875 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Lacrimam",
      "Osseus Pellebantus",
      "Tussock Triticum",
    ],
    cat: [],
  },
  {
    name: "Di Yomi",
    body: "C 7",
    coords: { x: 104.59375, y: -178.84375, z: 57.75 },
    infos: "",
    biologicals: ["Aleoida Gravis", "Clypeus Margaritus", "Stratum Tectonicas"],
    cat: [],
  },
  {
    name: "Samontia",
    body: "1 g",
    coords: { x: 30.96875, y: -191.09375, z: 130.15625 },
    infos: "",
    biologicals: [
      "Aleoida Gravis",
      "Clypeus Lacrimam",
      "Osseus Pellebantus",
      "Tussock Triticum",
    ],
    cat: [],
  },
];

categories = {
  Theme: {
    1: {
      name: "Incomplete",
      color: "FF0000",
    },
    2: {
      name: "In Progress",
      color: "FFA500",
    },
    3: {
      name: "Complete",
      color: "00FF00",
    },
    4: {
      name: "Reference system",
      color: "8888FF",
    },
  },
};
$biologicals = {
  "Cactoida Vermis": { image: "cactoida_vermis.png" },
  "Clypeus Lacrimam": { image: "clypeus_lacrimam.png" },
  "Frutexa Sponsae": { image: "frutexa_sponsae.png" },
  "Osseus Discus": { image: "osseus_discus.png" },
  "Tussock Virgam": { image: "tussock_virgam.png" },
  "Clypeus Margaritus": { image: "clypeus_margaritus.png" },
  "Stratum Tectonicas": { image: "stratum_tectonicas.png" },
};

// Append Sol as a reference point
systems.unshift({
  name: "Sol",
  coords: { x: 0, y: 0, z: 0 },
  infos: "The cradle of humanity. Included as a reference point.",
  cat: [4],
});

json_data = {
  systems: systems,
  categories: categories,
};
